# converted from gamslib nonsharp (NONSHARP, SEQ=120)
#
# Primary optimization model: the Generalized Benders' Decomposition MASTER
# problem (MIP) at the converged iteration of the nonsharp distillation
# sequence synthesis. The original GAMS file iterates an APROS/Benders loop
# (relaxed-primal NLP -> primal NLP -> master MIP). Only the master MIP carries
# a deterministic, standalone MILP objective (mu = 0.8938) and is converted
# here. The scenario / iterative re-solves (relax, primal, and the loop control)
# are dropped; the Lagrange / integer-cut coefficients generated during the run
# are captured as data.
import json
from pyomo.environ import *
import pyomo.environ as pyo

# ── OptiChat data loading ─────────────────────────────────────────────────────
# Data is injected into module globals as 'data' by OptiChat's callback_tool.
# The JSON uses the {sets, scalar_params, indexed_params} format with pipe-key
# notation for multi-dimensional params (e.g. "1|col-1": value -> (1, col-1): value).
data = globals().get("data", {})
# ─────────────────────────────────────────────────────────────────────────────

# ── model ───────────────────────────────────────────────────────────────────
model = pyo.ConcreteModel(doc="Nonsharp distillation sequence synthesis - Benders master MIP")

# Sets
model.col = pyo.Set(initialize=data["col"], ordered=True, doc="candidate distillation columns")
model.stm = pyo.Set(initialize=data["stm"], ordered=True, doc="column streams (top, bot)")
model.cp = pyo.Set(initialize=data["cp"], ordered=True, doc="feed components")
model.k = pyo.Set(initialize=data["k"], ordered=True, doc="Benders iterations (stored cuts)")

# savkey(col,stm,cp): key components per column stream (full superstructure)
model.savkey = pyo.Set(
    dimen=3,
    initialize=[tuple(key.split("|")) for key in data["savkey"]],
    doc="key components per column stream",
)

# Scalars
model.totfeed = pyo.Param(initialize=data["totfeed"], mutable=True, doc="total feed flow")
model.zlo = pyo.Param(initialize=data["zlo"], mutable=True, doc="lower bound on master solution")

# Single-index k-dicts arrive with string keys ("1"); the k set members are
# ints. Align the dict keys to the set's member type.
_kmap = {str(kk): kk for kk in data["k"]}


def _by_k(raw):
    return {_kmap.get(str(kk), kk): v for kk, v in raw.items()}


# Stored Lagrange / cut coefficients (generated by the Benders loop)
model.nfeas = pyo.Param(model.k, initialize=_by_k(data["nfeas"]), mutable=True, doc="primal feasibility flag (1 feasible)")
model.mcost = pyo.Param(model.k, model.col, initialize=data["mcost"], mutable=True, doc="stored alpha cost coeff")
model.ma1 = pyo.Param(model.k, model.col, initialize=data["ma1"], mutable=True, doc="stored a1 coeff")
model.ma2 = pyo.Param(model.k, model.col, model.stm, initialize=data["ma2"], mutable=True, doc="stored a2 coeff")
model.ma3 = pyo.Param(model.k, model.col, model.cp, initialize=data["ma3"], mutable=True, doc="stored a3 coeff")
model.mint = pyo.Param(model.k, model.col, initialize=data["mint"], mutable=True, doc="primal logical multiplier")
model.mlint = pyo.Param(model.k, model.col, initialize=data["mlint"], mutable=True, doc="relaxed-primal logical multiplier")
model.fink = pyo.Param(model.k, model.col, initialize=data["fink"], mutable=True, doc="stored column inlet flow")
model.reck = pyo.Param(
    model.k, model.col, model.stm, model.cp,
    initialize=data["reck"], mutable=True, default=0.0, doc="stored key recovery",
)
model.xkin = pyo.Param(model.k, model.col, model.cp, initialize=data["xkin"], mutable=True, doc="stored inlet composition")
model.cut = pyo.Param(model.k, initialize=_by_k(data["cut"]), mutable=True, doc="integer-cut RHS")
model.cutcol = pyo.Param(model.k, model.col, initialize=data["cutcol"], mutable=True, doc="integer-cut coeff")

# Variables
model.mu = pyo.Var(domain=pyo.Reals, doc="master solution (Benders lower bound)")
model.y = pyo.Var(model.col, domain=pyo.Binary, doc="existence of each column")

# ── constraints ───────────────────────────────────────────────────────────────
# bnd.. mu =g= zlo;
model.bnd = pyo.Constraint(expr=model.mu >= model.zlo, doc="lower bound on master solution")


def _objcoef(m, k, c):
    # (a1 + sum_{key} a2*rec + sum_cp a3*xin) evaluated at stored iterate k
    return (
        m.ma1[k, c]
        + sum(m.ma2[k, c, s] * m.reck[k, c, s, p] for (cc, s, p) in m.savkey if cc == c)
        + sum(m.ma3[k, c, p] * m.xkin[k, c, p] for p in m.cp)
    )


# lagrange(k)$(nfeas(k) = 1):  sum_col[ mcost*y + objcoef*fink ] + sum_col mint*(fink - totfeed*y) <= mu
def lagrange_rule(m, k):
    if abs(pyo.value(m.nfeas[k]) - 1.0) > 1e-9:
        return pyo.Constraint.Skip
    lhs = sum(m.mcost[k, c] * m.y[c] + _objcoef(m, k, c) * m.fink[k, c] for c in m.col)
    lhs += sum(m.mint[k, c] * (m.fink[k, c] - m.totfeed * m.y[c]) for c in m.col)
    return lhs <= m.mu


model.lagrange = pyo.Constraint(model.k, rule=lagrange_rule, doc="Lagrange cuts (feasible primals)")


# laerr(k)$(nfeas(k) = 0):  sum_col mlint*(fink - totfeed*y) <= 0
def laerr_rule(m, k):
    if abs(pyo.value(m.nfeas[k])) > 1e-9:
        return pyo.Constraint.Skip
    expr = sum(m.mlint[k, c] * (m.fink[k, c] - m.totfeed * m.y[c]) for c in m.col)
    if expr.__class__ in (int, float) and abs(float(expr)) < 1e-12:
        return pyo.Constraint.Skip  # trivial 0 <= 0 (all multipliers zero)
    return expr <= 0


model.laerr = pyo.Constraint(model.k, rule=laerr_rule, doc="feasibility cuts (infeasible primals)")


# intcut(k):  sum_col cutcol*y <= cut
def intcut_rule(m, k):
    return sum(m.cutcol[k, c] * m.y[c] for c in m.col) <= m.cut[k]


model.intcut = pyo.Constraint(model.k, rule=intcut_rule, doc="integer cuts")

# Objective: minimize mu
model.obj = pyo.Objective(expr=model.mu, sense=pyo.minimize, doc="minimize master solution mu")
