"""Regenerate WHATIF_WHYNOT_CHECKLIST.md from the clean rebuild aux + partition results.
Hsuan-Han 2026-06-12: queries finalized; convert to records, label any still-simple variable bounds
explicitly so he can revisit them. This produces a fresh, compact checklist (not an append)."""
import json, os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
aux = json.load(open(os.path.join(HERE, "_optichat_build_aux.json")))
part = json.load(open(os.path.join(HERE, "_optichat_partition.json"))) if os.path.exists(
    os.path.join(HERE, "_optichat_partition.json")) else None

checklist = aux["checklist"]   # simple variable bounds (deferred -> revisit)
manual = aux["manual"]         # tangled multi-statement heuristics (skipped per Hsuan-Han)

def group(items):
    g = defaultdict(list)
    for x in items:
        g[x["model"]].append(x)
    return g

out = []
out.append("# What-if / Why-not checklist — deferred items\n")
out.append("_Regenerated by `gen_checklist.py` from the clean rebuild on 2026-06-13 "
           "(after Hsuan-Han's second pass: 40 simple bounds promoted to substantive constraints, "
           "index-miss queries fixed, build script relaxed to keep def-rule constraints)._\n")
out.append("This file lists ONLY the queries that did **not** become dataset records, with full source "
           "so each is trackable. Everything else was built into `datasets/<model>_optichat_query.jsonl` "
           "and graded.\n")

import glob
live_files = glob.glob(os.path.join(HERE, "datasets", "*_optichat_query.jsonl"))
live_total = sum(sum(1 for _ in open(f)) for f in live_files)
if part:
    built = part["kept_total"] + len(part["quarantined"])
    rescued = live_total - part["kept_total"]
    remaining_quar = len(part["quarantined"]) - rescued
    out.append("## Build + grade summary (clean rebuild 2026-06-13)\n")
    out.append(f"- Dataset records built from finalized testing_library: **{built}**")
    out.append(f"- Passed reduced-instance self-grade: {part['kept_total']}")
    if len(part["quarantined"]) == 0:
        out.append("- Reduced-instance grading failures: **0** (Hsuan-Han's second pass rewrote the "
                   "previously index-missing queries to reference indices present in the reduced "
                   "grading instance, so no full-instance rescue was needed).")
    else:
        out.append(f"- Of the {len(part['quarantined'])} reduced-instance failures (index-misses on the "
                   f"small instance), **{rescued} rescued** on full-instance grading; **{remaining_quar} still "
                   "quarantined** (genuine grade failure — see §0).")
    out.append(f"- **FINAL dataset: {live_total} records across {len(live_files)} models**")
    out.append(f"- Vacuous-control kept (faithful but relation-flip control not caught): {part['vacuous']}\n")

# --- Section 0: records that failed grading and are NOT in the dataset (need fixing) ---
if part:
    have_pyomo = set()
    for f in live_files:
        for l in open(f):
            have_pyomo.add(json.loads(l)["expected_pyomo"])
    still = [q for q in part["quarantined"]
             if not any(h.startswith(q["pyomo"][:80]) for h in have_pyomo)]
    if still:
        out.append("## 0. FAILED grading — NOT in dataset (needs Hsuan-Han review)\n")
        out.append(f"**{len(still)} queries** failed self-grade even on the full instance — the constraint "
                   "references an index that does not exist in the model (genuine query error, not a harness "
                   "artifact). Excluded from the dataset; fix the query or drop it.\n")
        for q in still:
            out.append(f"- **{q['model']}** (rebuild idx {q['i']}) — _{q['query'][:80]}_")
            out.append(f"  - constraint: `{q['pyomo']}`")
            out.append(f"  - error: `{q['reason'][:90]}`")
        out.append("")

# --- Section 1: simple variable bounds still to revisit ---
out.append("## 1. Simple variable bounds — STILL TO REVIEW (Hsuan-Han)\n")
out.append(f"**{len(checklist)} queries** are still a single decision variable fixed to a constant "
           "(`model.x[...] == c`). These were intentionally left as variable bounds; Hsuan-Han will make "
           "them more substantive later. Routed here, NOT into the dataset.\n")
g = group(checklist)
for model in sorted(g):
    out.append(f"### {model}  ({len(g[model])})")
    out.append(f"_source: `testing_library/feas_test/{model}.txt`_\n")
    out.append("| type | subtype | query | constraint (var fix) |")
    out.append("|---|---|---|---|")
    for x in g[model]:
        q = x["query"].replace("|", "\\|").replace("\n", " ")[:90]
        c = x["constraint"].replace("|", "\\|").replace("\n", " ")
        out.append(f"| {x['type']} | {x['subtype']} | {q} | `{c}` |")
    out.append("")

# --- Section 2: tangled heuristics (skipped) ---
out.append("## 2. Tangled why-not heuristics — SKIPPED (recorded only)\n")
out.append(f"**{len(manual)} queries** are multi-statement heuristics (loops / computed fixes / mixed "
           "fix+constraint). Per Hsuan-Han these are skipped for now and only recorded. Each shows the "
           "model and the raw heuristic head so it can be found.\n")
gm = group(manual)
for model in sorted(gm):
    out.append(f"### {model}  ({len(gm[model])})")
    out.append(f"_source: `testing_library/feas_test/{model}.txt`_\n")
    for x in gm[model]:
        head = x["constraint"].split("\n")
        head = [h for h in head if h.strip() and not h.strip().startswith("model = load_model")]
        snippet = " / ".join(head[:3])[:160].replace("\n", " ")
        q = x["query"].replace("\n", " ")[:80]
        out.append(f"- **{x['type']}/{x['subtype']}** — _{q}_ → `{snippet}`")
    out.append("")

open(os.path.join(HERE, "WHATIF_WHYNOT_CHECKLIST.md"), "w").write("\n".join(out))
print(f"wrote WHATIF_WHYNOT_CHECKLIST.md: {len(checklist)} simple bounds, {len(manual)} heuristics")
